package com.bsoft.wsClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CommonInterface service = new CommonInterface();
 * CommonInterfaceSoap portType = service.getCommonInterfaceSoap();
 * portType.funMain(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CommonInterface", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.26.28.127:9088/CommonInterface.asmx?WSDL")
public class CommonInterface extends Service {

	private final static URL COMMONINTERFACE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(CommonInterface.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = CommonInterface.class.getResource(".");
			url = new URL(baseUrl,
					"http://192.26.28.127:9088/CommonInterface.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.26.28.127:9088/CommonInterface.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		COMMONINTERFACE_WSDL_LOCATION = url;
	}

	public CommonInterface(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CommonInterface() {
		super(COMMONINTERFACE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"CommonInterface"));
	}

	/**
	 * 
	 * @return returns CommonInterfaceSoap
	 */
	@WebEndpoint(name = "CommonInterfaceSoap")
	public CommonInterfaceSoap getCommonInterfaceSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"CommonInterfaceSoap"), CommonInterfaceSoap.class);
	}

	/**
	 * 
	 * @return returns CommonInterfaceSoap
	 */
	@WebEndpoint(name = "CommonInterfaceSoap12")
	public CommonInterfaceSoap getCommonInterfaceSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"CommonInterfaceSoap12"), CommonInterfaceSoap.class);
	}

}
