package com.bsoft.wsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HdyyElectronicServicePortType", targetNamespace = "http://service.eastpharm.com.cn")
public interface HdyyElectronicServicePortType {

	/**
	 * 
	 * @param requestXml
	 * @param userid
	 * @param requestType
	 * @param password
	 * @return returns java.lang.String
	 * @throws HdyyElectronicServiceException_Exception
	 */
	@WebMethod(action = "urn:doRequestWithXML")
	@WebResult(targetNamespace = "http://service.eastpharm.com.cn")
	@RequestWrapper(localName = "doRequestWithXML", targetNamespace = "http://service.eastpharm.com.cn", className = "phis.source.ws.hdwsClient.DoRequestWithXML")
	@ResponseWrapper(localName = "doRequestWithXMLResponse", targetNamespace = "http://service.eastpharm.com.cn", className = "phis.source.ws.hdwsClient.DoRequestWithXMLResponse")
	public String doRequestWithXML(
            @WebParam(name = "userid", targetNamespace = "http://service.eastpharm.com.cn") String userid,
            @WebParam(name = "password", targetNamespace = "http://service.eastpharm.com.cn") String password,
            @WebParam(name = "requestType", targetNamespace = "http://service.eastpharm.com.cn") String requestType,
            @WebParam(name = "requestXml", targetNamespace = "http://service.eastpharm.com.cn") String requestXml)
			throws HdyyElectronicServiceException_Exception;

	/**
	 * 
	 * @param userid
	 * @param requestType
	 * @param password
	 * @return returns java.lang.String
	 * @throws HdyyElectronicServiceException_Exception
	 */
	@WebMethod(action = "urn:doRequest")
	@WebResult(targetNamespace = "http://service.eastpharm.com.cn")
	@RequestWrapper(localName = "doRequest", targetNamespace = "http://service.eastpharm.com.cn", className = "phis.source.ws.hdwsClient.DoRequest")
	@ResponseWrapper(localName = "doRequestResponse", targetNamespace = "http://service.eastpharm.com.cn", className = "phis.source.ws.hdwsClient.DoRequestResponse")
	public String doRequest(
            @WebParam(name = "userid", targetNamespace = "http://service.eastpharm.com.cn") String userid,
            @WebParam(name = "password", targetNamespace = "http://service.eastpharm.com.cn") String password,
            @WebParam(name = "requestType", targetNamespace = "http://service.eastpharm.com.cn") String requestType)
			throws HdyyElectronicServiceException_Exception;

}
