package com.bsoft.wsClient;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "HdyyElectronicServiceException", targetNamespace = "http://service.eastpharm.com.cn")
public class HdyyElectronicServiceException_Exception extends
		Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private HdyyElectronicServiceException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public HdyyElectronicServiceException_Exception(String message,
			HdyyElectronicServiceException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public HdyyElectronicServiceException_Exception(String message,
			HdyyElectronicServiceException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         cn.com.eastpharm.service.HdyyElectronicServiceException
	 */
	public HdyyElectronicServiceException getFaultInfo() {
		return faultInfo;
	}

}
